services:
  - type: web
    name: my-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "waitress-serve --port=8000 app:app"
    envVars:
      - key: PORT
        value: 8000
