services:
  - type: web
    name: progrify-backend
    env: python
    buildCommand: |
      cd backend
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "gunicorn --workers=1 --threads=1 --worker-tmp-dir /dev/shm --bind 0.0.0.0:8000 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: $PORT
