services:
  - type: web
    name: progrify
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 5000
    plan: free
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
