services:
- type: web
  name: progrify-backend
  env: python
  buildCommand: |
    python -m venv venv
    . venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: cd backend && gunicorn app:app --workers 4 --threads 2
  envVars:
  - key: PYTHON_VERSION
    value: 3.11.9
  - key: FLASK_ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: 1