services:
- type: web
  name: progrify-backend
  env: python
  buildCommand: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
  envVars:
  - key: PYTHON_VERSION
    value: 3.11.9
  - key: FLASK_ENV
    value: production