services:
- type: web
  name: progrify-backend
  env: python
  buildCommand: |
    python -m venv venv
    . venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: cd /opt/render/project/src/backend && gunicorn app:app
  envVars:
  - key: PYTHON_VERSION
    value: 3.11.9
  - key: FLASK_ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: 1
  - key: PORT
    value: 10000