services:
  - type: web
    name: progrify-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000 --timeout 120
    envVars:
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
      - key: MAIL_SERVER
        fromEnvVar: MAIL_SERVER
      - key: MAIL_PORT
        fromEnvVar: MAIL_PORT
      - key: MAIL_USE_TLS
        fromEnvVar: MAIL_USE_TLS
      - key: MAIL_USERNAME
        fromEnvVar: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromEnvVar: MAIL_PASSWORD
    healthCheckPath: /api/health
