services:
- type: web
  name: progrify-backend
  env: python
  buildCommand: |
    python -m venv venv
    . venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    pwd
    ls -R /opt/render/project/src
  startCommand: |
    cd /opt/render/project/src/backend
    pwd
    ls
    ls ../frontend
    gunicorn --workers 4 --threads 2 app:app
  envVars:
  - key: PYTHON_VERSION
    value: 3.11.9
  - key: FLASK_ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: 1
  - key: PORT
    value: 10000
  - key: PROJECT_ROOT
    value: /opt/render/project/src
  - key: FRONTEND_PATH
    value: /opt/render/project/src/frontend